import type {
  FeatureImportance,
  MockLog,
  ModelVersion,
  NavItem,
  PatientRecord,
  PredictionQueueRow,
  PredictionTaskDefinition,
  PreprocessStep,
  TaskRecord,
} from './types';

export const navItems: NavItem[] = [
  { id: 'workbench', label: '工作台', description: '汇总今日队列、复核提醒和预测概览' },
  { id: 'batch', label: '批量导入', description: '导入患者清单、EO/EC EEG 和临床表格' },
  { id: 'preprocess', label: '预处理', description: '配置移除电极、重参考和坏导插值' },
  { id: 'feature', label: '特征提取', description: '生成 EEG 频域、连接和复杂度特征' },
  { id: 'archive', label: '病例库', description: '检索患者记录、原始数据和处理状态' },
  { id: 'models', label: '模型库', description: '管理已验证模型版本和性能指标' },
  { id: 'predict', label: '预测队列', description: '运行 Residual 结局预测并追踪进度' },
  { id: 'interpret', label: '解释分析', description: '查看个体解释和全局特征重要性' },
  { id: 'report', label: '报告中心', description: '生成、复核和签发临床预测报告' },
  { id: 'settings', label: '系统设置', description: '维护通道模板、阈值和账号权限' },
];

export const mockPatients: PatientRecord[] = [
  {
    id: 'P-2026-001',
    name: '张敏',
    age: 62,
    sex: '女',
    diagnosis: '缺血性卒中',
    affectedHand: '右手',
    eo: true,
    ec: true,
    preprocessStatus: '已完成',
    featureStatus: '已完成',
    task: 'tACS 后 4 周运动残余预测',
    prediction: 'Residual <= 1.5',
    probability: 0.74,
    probabilityLabel: 'Residual <= 1.5',
    reportStatus: '草稿',
    updatedAt: '2026-05-28 10:40',
  },
  {
    id: 'P-2026-002',
    name: '李伟',
    age: 57,
    sex: '男',
    diagnosis: '脑出血恢复期',
    affectedHand: '左手',
    eo: true,
    ec: false,
    preprocessStatus: '处理中',
    featureStatus: '待处理',
    task: 'tACS 后 4 周运动残余预测',
    prediction: null,
    probability: null,
    probabilityLabel: 'Residual <= 1.5',
    reportStatus: '未生成',
    updatedAt: '2026-05-28 10:18',
  },
  {
    id: 'P-2026-003',
    name: '陈芳',
    age: 69,
    sex: '女',
    diagnosis: '缺血性卒中',
    affectedHand: '右手',
    eo: true,
    ec: true,
    preprocessStatus: '已完成',
    featureStatus: '已完成',
    task: 'tACS 后 4 周运动残余预测',
    prediction: 'Residual > 1.5',
    probability: 0.31,
    probabilityLabel: 'Residual <= 1.5',
    reportStatus: '已生成',
    updatedAt: '2026-05-27 16:05',
  },
];

export const mockTasks: TaskRecord[] = [
  {
    id: 'T-1001',
    patientId: 'P-2026-001',
    patientName: '张敏',
    task: '报告复核',
    stage: '医生确认解释结果',
    status: '需复核',
    assignee: '康复科刘医生',
    updatedAt: '2026-05-28 10:42',
  },
  {
    id: 'T-1002',
    patientId: 'P-2026-002',
    patientName: '李伟',
    task: '静息态 EEG 预处理',
    stage: '等待确认坏导',
    status: '处理中',
    assignee: '技师王',
    updatedAt: '2026-05-28 10:18',
  },
  {
    id: 'T-1003',
    patientId: 'P-2026-003',
    patientName: '陈芳',
    task: '预测报告归档',
    stage: '报告中心',
    status: '已完成',
    assignee: '系统',
    updatedAt: '2026-05-27 16:20',
  },
];

export const mockLogs: MockLog[] = [
  {
    id: 'L-001',
    time: '2026-05-28 09:32',
    level: 'info',
    source: '批量导入',
    message: '已读取 64 个 EEG 通道和 4 个辅助通道',
  },
  {
    id: 'L-002',
    time: '2026-05-28 09:37',
    level: 'warning',
    source: '预处理',
    message: 'M1 已被加入移除列表，无法使用 M1/M2 重参考',
  },
  {
    id: 'L-003',
    time: '2026-05-28 10:20',
    level: 'info',
    source: '预测队列',
    message: 'stroke-tacs-eeg-clinical v2.4.0 已完成 P-2026-001',
  },
];

export const preprocessSteps: PreprocessStep[] = [
  {
    id: 'remove-empty-electrodes',
    title: '移除空电极',
    description: '由用户选择需要排除的 EEG 电极，辅助通道不参与坏导插值',
    enabled: true,
  },
  {
    id: 'reference-average',
    title: '平均重参考',
    description: '对保留 EEG 通道执行 average 重参考',
    enabled: true,
    referenceMode: 'average',
  },
  {
    id: 'reference-m1m2',
    title: 'M1/M2 重参考',
    description: '仅在 M1、M2 未被移除时可选',
    enabled: false,
    referenceMode: 'm1m2',
  },
  {
    id: 'interpolate-bad-leads',
    title: '坏导插值',
    description: '仅对未移除的 EEG 通道生成候选列表',
    enabled: true,
  },
];

export const predictionTasks: PredictionTaskDefinition[] = [
  {
    id: 'PT-001',
    taskId: 'residual-4w',
    name: 'tACS 后 4 周运动残余预测',
    target: '4 周后运动功能残余等级',
    labelDefinition: 'Residual <= 1.5',
    positiveLabel: '低残余风险',
    horizon: '4 周',
    description: '以 Residual <= 1.5 作为阳性标签，评估患者对 tACS 康复干预的反应概率',
  },
  {
    id: 'PT-002',
    taskId: 'residual-8w',
    name: 'tACS 后 8 周运动残余预测',
    target: '8 周后运动功能残余等级',
    labelDefinition: 'Residual <= 1.5',
    positiveLabel: '低残余风险',
    horizon: '8 周',
    description: '延长随访窗口，用于报告中心生成中期康复趋势',
  },
];

export const modelVersions: ModelVersion[] = [
  {
    id: 'MV-EEG-230',
    taskId: 'residual-4w',
    name: 'stroke-tacs-eeg',
    version: 'v2.3.0',
    inputType: 'EEG-only',
    inputs: ['EO EEG features', 'EC EEG features'],
    validation: '2026Q2 留出验证集',
    accuracy: 0.81,
    balancedAccuracy: 0.78,
    rocAuc: 0.86,
    prAuc: 0.83,
    status: '当前版本',
    releasedAt: '2026-05-20',
  },
  {
    id: 'MV-CLIN-240',
    taskId: 'residual-4w',
    name: 'stroke-tacs-eeg-clinical',
    version: 'v2.4.0',
    inputType: 'EEG+Clinical',
    inputs: ['EO EEG features', 'EC EEG features', 'age', 'affectedHand', 'baselineResidual'],
    validation: '2026Q2 分层交叉验证',
    accuracy: 0.84,
    balancedAccuracy: 0.82,
    rocAuc: 0.89,
    prAuc: 0.87,
    status: '候选版本',
    releasedAt: '2026-05-27',
  },
  {
    id: 'MV-EEG-210',
    taskId: 'residual-8w',
    name: 'stroke-tacs-eeg',
    version: 'v2.1.0',
    inputType: 'EEG-only',
    inputs: ['EO EEG features', 'EC EEG features'],
    validation: '2026Q1 留出验证集',
    accuracy: 0.77,
    balancedAccuracy: 0.74,
    rocAuc: 0.82,
    prAuc: 0.79,
    status: '归档版本',
    releasedAt: '2026-04-12',
  },
];

export const predictionQueue: PredictionQueueRow[] = [
  {
    id: 'Q-001',
    patientId: 'P-2026-001',
    patientName: '张敏',
    taskId: 'residual-4w',
    priority: '常规',
    status: '已完成',
    hasEegFeatures: true,
    hasClinical: true,
    prediction: 'Residual <= 1.5',
    probability: 0.74,
    probabilityLabel: 'Residual <= 1.5',
    modelUsed: 'stroke-tacs-eeg-clinical v2.4.0',
    explanationStatus: '已生成',
    submittedAt: '2026-05-28 10:10',
  },
  {
    id: 'Q-002',
    patientId: 'P-2026-002',
    patientName: '李伟',
    taskId: 'residual-4w',
    priority: '加急',
    status: '待处理',
    hasEegFeatures: false,
    hasClinical: true,
    prediction: null,
    probability: null,
    probabilityLabel: 'Residual <= 1.5',
    modelUsed: 'stroke-tacs-eeg-clinical v2.4.0',
    explanationStatus: '未生成',
    submittedAt: '2026-05-28 10:18',
  },
  {
    id: 'Q-003',
    patientId: 'P-2026-003',
    patientName: '陈芳',
    taskId: 'residual-4w',
    priority: '常规',
    status: '已完成',
    hasEegFeatures: true,
    hasClinical: false,
    prediction: 'Residual > 1.5',
    probability: 0.31,
    probabilityLabel: 'Residual <= 1.5',
    modelUsed: 'stroke-tacs-eeg v2.3.0',
    explanationStatus: '需复核',
    submittedAt: '2026-05-27 15:48',
  },
];

export const globalFeatureImportance: FeatureImportance[] = [
  {
    id: 'FI-001',
    modelId: 'MV-CLIN-240',
    feature: 'affected_m1_beta_power',
    label: '患侧 M1 beta 功率',
    category: '频域特征',
    importance: 0.24,
    direction: '正向',
  },
  {
    id: 'FI-002',
    modelId: 'MV-CLIN-240',
    feature: 'frontal_theta_alpha_ratio',
    label: '前额叶 theta/alpha 比值',
    category: '频域特征',
    importance: 0.18,
    direction: '负向',
  },
  {
    id: 'FI-003',
    modelId: 'MV-CLIN-240',
    feature: 'interhemispheric_coherence',
    label: '半球间相干性',
    category: '连接特征',
    importance: 0.16,
    direction: '正向',
  },
  {
    id: 'FI-004',
    modelId: 'MV-CLIN-240',
    feature: 'baseline_residual',
    label: '基线 Residual',
    category: '临床特征',
    importance: 0.14,
    direction: '负向',
  },
  {
    id: 'FI-005',
    modelId: 'MV-EEG-230',
    feature: 'ec_alpha_asymmetry',
    label: '闭眼 alpha 半球不对称性',
    category: '频域特征',
    importance: 0.11,
    direction: '正向',
  },
];
